version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging into AWS ECR
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image
      - docker build -f aws/Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...
artifacts:
  files: imagedefinitions.json
