version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image
      - docker build -f aws/Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: imagedefinitions.json
